const jokes = [
  "Why don't scientists trust atoms? Because they make up everything!",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "What do you call fake spaghetti? An impasta!",
  "Why did the bicycle fall over? It was two-tired.",
  "What do you call cheese that isn't yours? Nacho cheese!",
  "Why can't your nose be 12 inches long? Because then it would be a foot.",
  "Why did the math book look sad? Because it had too many problems.",
  "What do you call a fish wearing a bowtie? Sofishticated.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "Why did the tomato turn red? Because it saw the salad dressing!",
  "Why don’t eggs tell jokes? They’d crack each other up.",
  "What do you call a belt made of watches? A waist of time.",
  "Why did the cookie go to the hospital? Because it felt crummy.",
  "What do you call a bear with no teeth? A gummy bear.",
  "Why did the computer go to therapy? It had too many bytes.",
  "How do you organize a space party? You planet.",
  "Why did the chicken join a band? Because it had the drumsticks.",
  "Why don’t oysters share their pearls? Because they’re shellfish.",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "Why did the coffee file a police report? It got mugged.",
  "Why did the banana go to the doctor? It wasn’t peeling well.",
  "What do you call a sleeping bull? A bulldozer.",
  "Why are elevator jokes so good? They work on many levels.",
  "Why did the man run around his bed? He was trying to catch up on sleep.",
  "What do you call a cow with no legs? Ground beef.",
  "Why did the frog take the bus to work? His car got toad away.",
  "Why did the music teacher go to jail? Because she got caught with too many notes.",
  "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
  "What do you call a dog magician? A labracadabrador.",
  "Why did the grape stop in the middle of the road? It ran out of juice.",
  "Why did the pencil get detention? It was drawing too much attention.",
  "Why did the broom get promoted? It swept the competition.",
  "Why did the cow win an award? For being outstanding in her field.",
  "What do you call a pig that knows karate? A pork chop.",
  "Why did the astronaut break up with his girlfriend? He needed space.",
  "Why did the duck get a job? He was a quack developer.",
  "Why did the pirate go to school? To improve his arrrrrticulation.",
  "Why did the cat sit on the computer? To keep an eye on the mouse.",
  "Why did the man put his money in the blender? He wanted to make liquid assets.",
  "Why did the fish blush? Because it saw the ocean’s bottom.",
  "Why did the tree go to therapy? It had too many issues rooted in childhood.",
  "Why did the bee get married? Because he found his honey.",
  "Why did the light bulb go to school? To get a little brighter.",
  "Why did the calendar get promoted? It had a lot of dates.",
  "Why did the shoe go to the party alone? It didn’t have a sole mate.",
  "Why did the robot go on vacation? It needed to recharge.",
  "Why did the squirrel bring a ladder? To get to the high nuts.",
  "Why did the baker go broke? He couldn’t make enough dough.",
  "Why did the owl become a professor? Because it was a wise guy.",
  "Why did the keyboard break up with the mouse? It felt clicked out.",
  "Why did the potato sit down? It was feeling fried.",
  "Why did the mirror get in trouble? It was reflecting poorly.",
  "Why did the cloud date the sun? It was a bright idea.",
  "Why did the kangaroo stop boxing? It lost its bounce.",
  "Why did the volcano break up with the mountain? It felt too explosive.",
  "Why did the spider become a web developer? It loved networking.",
  "Why did the donut go to therapy? It felt empty inside.",
  "Why did the snail paint an S on his car? So people would say, 'Look at that S-car go!'",
  "Why did the ghost go to school? To improve his boo-k smarts.",
  "Why did the chicken cross the playground? To get to the other slide.",
  "Why did the dog sit in the shade? He didn’t want to be a hot dog.",
  "Why did the frog call his insurance company? He had a jump in his car.",
  "Why did the horse become a singer? He had the neighs.",
  "Why did the lion eat the tightrope walker? He wanted a well-balanced meal.",
  "Why did the crab never share? Because he was a little shellfish.",
  "Why did the cat become a DJ? It had the purrfect mix.",
  "Why did the turtle cross the road? To get to the shell station.",
  "Why did the ant bring a suitcase? It was going on a picnic.",
  "Why did the moon skip dinner? It was full.",
  "Why did the star go to school? To become a brighter star.",
  "Why did the pencil break up with the eraser? It couldn’t handle the mistakes.",
  "Why did the sandwich go to the gym? To get shredded.",
  "Why did the ice cream truck break down? It had a meltdown.",
  "Why did the balloon go to school? To rise to the occasion.",
  "Why did the cookie cry? Because its mom was a wafer too long.",
  "Why did the robot fail art class? It couldn’t draw emotions.",
  "Why did the book join the gym? It wanted to get its spine in shape.",
  "Why did the apple stop rolling? It ran out of core strength.",
  "Why did the penguin become a detective? It loved cold cases.",
  "Why did the giraffe get bad grades? It had its head in the clouds.",
  "Why did the elephant bring a suitcase? It was packing its trunk.",
  "Why did the dolphin fail math? It couldn’t count on its fins.",
  "Why did the cactus get a job? It was looking for a prickly situation.",
  "Why did the mushroom get invited to the party? Because he was a fungi.",
  "Why did the squirrel start a podcast? It had a lot of nuts to share.",
  "Why did the goat become a rapper? It was the G.O.A.T.",
  "Why did the penguin sit on the iceberg? It was chilling.",
  "Why did the raccoon become a thief? It had a mask already.",
  "Why did the snail get a speeding ticket? It was on a roll.",
  "Why did the fish start a band? It had great scales.",
  "Why did the cat become a banker? It had nine lives of savings.",
  "Why did the dog become a chef? It had a barkery.",
  "Why did the bee start a business? It wanted to buzzness.",
  "Why did the cow become a DJ? It dropped the beef.",
  "Why did the duck become a lawyer? It was good at quacking cases.",
  "Why did the horse become a therapist? It knew how to rein in emotions.",
  "Why did the pig become a pilot? It wanted to soar like bacon.",
  "Why did the chicken become a scientist? It cracked the egg code.",
  "Why did the llama become a poet? It had deep wooly thoughts."
];
let num=Math.floor(Math.random()*100)
console.log(num)
let rand=document.getElementsByTagName("h1")
let jok = jokes[num]
document.write(`${num} : ${jok}`)
