let a = document.getElementById("first")
console.log(a)
console.log(a.attributes)
console.log(a.getAttribute("class"))
console.log(a.hasAttribute("class"))
console.log(a.hasAttribute("style"))
a.setAttribute("class","true ashvini")
a.removeAttribute("class")
console.log(a.dataset)
console.log(a.dataset.game)
console.log(a.dataset.player)
// let l=a.setAttribute("hiddden","true")
// console.log(l)